export const add = (a: number) => (b: number) => a + b;
export const sub = (a: number) => (b: number) => a - b;
export const mul = (a: number) => (b: number) => a * b;
export const div = (a: number) => (b: number) => a / b;
export const mod = (a: number) => (b: number) => a % b;
export const pow = (a: number) => (b: number) => a ** b;
export const sqrt = (a: number) => Math.sqrt(a);
export const abs = (a: number) => Math.abs(a);
export const min = (a: number) => (b: number) => Math.min(a, b);
export const max = (a: number) => (b: number) => Math.max(a, b);
